import Header from '@/components/HomePage/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Footer } from '@/components/HomePage/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
